name: Stock One UI 5 Rom Mod

on:
  workflow_dispatch:
    inputs:
      MODEL:
        description: "Device Model"
        required: true
        default: "SM-A225F"
      CSC:
        description: "CSC Code"
        required: true
        default: "BKD"
      IMEI:
        description: "IMEI Number"
        required: true
        default: "350167020473859"
      ROM_TYPE:
        description: "ROM Type (e.g. Stock, Target)"
        required: true
        default: "Stock"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing required packages
      run: |
        chmod +x ./scripts/install_packages.sh
        sudo bash ./scripts/install_packages.sh

    - name: Downloading / extracting firmware
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.MODEL }} \
          ${{ github.event.inputs.CSC }} \
          ${{ github.event.inputs.IMEI }} \
          ${{ github.event.inputs.ROM_TYPE }}

    - name: Start making ROM
      run: |
        chmod +x ./scripts/make_rom.sh
        sudo bash ./scripts/make_rom.sh
