name: QuantumROM Tools.

on:
  workflow_dispatch:
    inputs:
      # Support Device Model
      SUPPORT_MODEL:
        description: "=== MAKE ROM FOR === Device Model"
        required: true
        default: "SM-S711B"
      
      # TARGET rom section
      TARGET_MODEL:
        description: "=== TARGET ROM SECTION === Device Model"
        required: true
        default: "SM-S711B"
      TARGET_CSC:
        description: "TARGET: CSC Code"
        required: true
        default: "BKD"
      TARGET_IMEI:
        description: "TARGET: IMEI Number"
        required: true
        default: "350167020473859"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate device support.
      run: |
        if [ ! -d "./QuantumROM/Devices/${{ GITHUB.EVENT.INPUTS.STOCK_MODEL }}" ]; then
          echo "❌ Your device '${{ github.event.inputs.SUPPORT_MODEL }}' is not ready for port target ROM."
          exit 1
        fi

    - name: Installing required packages
      run: |
        chmod +x ./scripts/install_packages.sh
        sudo bash ./scripts/install_packages.sh

    - name: Downloading / extracting STOCK firmware
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.STOCK_MODEL }} \
          ${{ github.event.inputs.STOCK_CSC }} \
          ${{ github.event.inputs.STOCK_IMEI }} \
          ${{ github.event.inputs.STOCK_ROM_TYPE }}

    - name: Downloading / extracting TARGET firmware
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.TARGET_MODEL }} \
          ${{ github.event.inputs.TARGET_CSC }} \
          ${{ github.event.inputs.TARGET_IMEI }} \
          ${{ github.event.inputs.TARGET_MODEL }} \

    - name: Start making ROM
      run: |
        chmod +x ./scripts/make_rom.sh
        sudo bash ./scripts/make_rom.sh      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.MODEL }} \
          ${{ github.event.inputs.CSC }} \
          ${{ github.event.inputs.IMEI }} \
          ${{ github.event.inputs.ROM_TYPE }}

    - name: Start making ROM
      run: |
        chmod +x ./scripts/make_rom.sh
        sudo bash ./scripts/make_rom.sh
