name: Stock One UI 5 Rom Mod

on:
  workflow_dispatch:
    inputs:
      # STOCK rom section
      STOCK_MODEL:
        description: "=== STOCK SECTION === Device Model"
        required: true
        default: "SM-A225F"
      STOCK_CSC:
        description: "STOCK: CSC Code"
        required: true
        default: "BKD"
      STOCK_IMEI:
        description: "STOCK: IMEI Number"
        required: true
        default: "350167020473859"
      STOCK_ROM_TYPE:
        description: "STOCK: ROM Type (e.g. Stock, Debloated)"
        required: true
        default: "Stock"

      # TARGET rom section
      TARGET_MODEL:
        description: "TARGET: Device Model"
        required: true
        default: "SM-A225F"
      TARGET_CSC:
        description: "TARGET: CSC Code"
        required: true
        default: "BKD"
      TARGET_IMEI:
        description: "TARGET: IMEI Number"
        required: true
        default: "350167020473859"
      TARGET_ROM_TYPE:
        description: "[TARGET] Device Model"
        required: true
        default: "Debloated"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing required packages
      run: |
        chmod +x ./scripts/install_packages.sh
        sudo bash ./scripts/install_packages.sh

    - name: Downloading / extracting STOCK firmware
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.STOCK_MODEL }} \
          ${{ github.event.inputs.STOCK_CSC }} \
          ${{ github.event.inputs.STOCK_IMEI }} \
          ${{ github.event.inputs.STOCK_ROM_TYPE }}

    - name: Downloading / extracting TARGET firmware
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.TARGET_MODEL }} \
          ${{ github.event.inputs.TARGET_CSC }} \
          ${{ github.event.inputs.TARGET_IMEI }} \
          ${{ github.event.inputs.TARGET_ROM_TYPE }}

    - name: Start making ROM
      run: |
        chmod +x ./scripts/make_rom.sh
        sudo bash ./scripts/make_rom.sh      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh \
          ${{ github.event.inputs.MODEL }} \
          ${{ github.event.inputs.CSC }} \
          ${{ github.event.inputs.IMEI }} \
          ${{ github.event.inputs.ROM_TYPE }}

    - name: Start making ROM
      run: |
        chmod +x ./scripts/make_rom.sh
        sudo bash ./scripts/make_rom.sh
